# Generated by Django 2.0.4 on 2018-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedacademy',
            name='activation_callback_url',
            field=models.URLField(blank=True, help_text='The URL which will be presented to the user in the activation email.', null=True, verbose_name='Activation Callback URL'),
        ),
        migrations.AddField(
            model_name='sharedacademy',
            name='reset_password_callback_url',
            field=models.URLField(blank=True, help_text='The URL which will be presented to the user was requested a password reset url in the email.', null=True, verbose_name='Reset Password Callback URL'),
        ),
    ]
