# Generated by Django 2.0.4 on 2018-04-08 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared_foundation', '0002_auto_20180408_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareduser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareduser',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
