# Generated by Django 2.0.4 on 2018-04-09 23:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', help_text='The title of this course.', max_length=63, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', help_text='The description of this lecture.', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'db_table': 'at_lectures',
            },
        ),
        migrations.CreateModel(
            name='LectureOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_num', models.PositiveSmallIntegerField(db_index=True, help_text='The lecture number this is.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Lecture Number')),
                ('week_num', models.PositiveSmallIntegerField(blank=True, default=1, help_text='The week number this lecture is on.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Week Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Lecture Order',
                'verbose_name_plural': 'Lecture Orders',
                'db_table': 'at_lecture_orders',
                'ordering': ['week_num', 'lecture_num'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='The title of this slide.', max_length=63, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='The slide description.', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('lecture', models.ForeignKey(blank=True, help_text='The lecture this slide belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_slide_lecture_related', to='tenant_foundation.Lecture')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'db_table': 'at_slides',
            },
        ),
        migrations.CreateModel(
            name='SlideOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveSmallIntegerField(help_text='The order number this slide belongs to in the lecture.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Order Number')),
                ('lecture', models.ForeignKey(help_text='The lecture this belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_slideorder_lecture_related', to='tenant_foundation.Lecture')),
                ('slide', models.ForeignKey(help_text='The slide this belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_slideorder_lecture_related', to='tenant_foundation.Slide')),
            ],
            options={
                'verbose_name': 'Slide Order',
                'verbose_name_plural': 'Slide Orders',
                'db_table': 'at_slide_orders',
                'ordering': ['order_num'],
            },
        ),
        migrations.AlterModelTable(
            name='course',
            table='at_courses',
        ),
        migrations.AddField(
            model_name='lectureorder',
            name='course',
            field=models.ForeignKey(help_text='The course this lecture belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_lectureorder_course_related', to='tenant_foundation.Course'),
        ),
        migrations.AddField(
            model_name='lectureorder',
            name='lecture',
            field=models.ForeignKey(help_text='The lecture this belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_lectureorder_lecture_related', to='tenant_foundation.Lecture'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this lecture belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_foundation_lecture_course_related', to='tenant_foundation.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.ManyToManyField(related_name='tenant_foundation_course_course_related', through='tenant_foundation.LectureOrder', to='tenant_foundation.Lecture'),
        ),
    ]
