# Generated by Django 2.0.4 on 2018-04-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_foundation', '0002_auto_20180409_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lectureorder',
            name='last_modified_at',
        ),
    ]
